version: '3.1'

services:
  api:
    build: .
    container_name: mostdev_api
    ports:
      - 8086:8080
    working_dir: /yacht/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mostdev-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/mostdev-mongo:/data/db
      - $HOME/data/mostdev-mongo:/data/bkp